### ISSUE TITLE
Add correct version number

### ISSUE THREAD

**Issue by gep13** [chwilfing/chocolatey#2]
Regarding this package:

https://chocolatey.org/packages/azure-information-protection-client/0.2

I know that I just approved it, but could you push a new package version that includes the actual current version number, i.e. 1.26.6.0

Thanks

**Comment by chwilfing** [comment]
sorry for the late response, package version was updated and pushed to public repo. should align with actual version number.

**Comment by gep13** [comment]
@chwilfing that is great, thank you!
